version: '3'
services:
  settlegram:
    build: ./SettleGram
    restart: always 
    env_file:
      - ./secrets.env
    command: python -u main.py
    environment:
        PYTHONUNBUFFERED: 1
    depends_on:
      - mongodb
    networks:
      - mynetwork
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./db-data:/data/db
    networks:
      - mynetwork

volumes:
  db-data:
   external: true

networks:
  mynetwork:
